#!/bin/python3

import os

pen_name = "HUION PenTablet Pen stylus"

status_txt = os.path.expanduser("~/bin/status.txt")
begin = open(status_txt, 'r')
readIt = begin.read().splitlines()[0]
begin.close()

def switch(head, display):
    os.system('xsetwacom set "'+pen_name+'" MapToOutput '+head)
    current_status = open(status_txt, "w")
    current_status.write(display)
    current_status.close()

if "main" == readIt:
    switch("Head-1", "second")
else:
    switch("Head-0", "main")